apiVersion: v1
kind: Secret
metadata:
  name: vegasystems-credentials
  namespace: cert-manager
type: Opaque
stringData:
  apiUser: "REPLACE_WITH_VEGASYSTEMS_USER"
  apiKey:  "REPLACE_WITH_VEGASYSTEMS_KEY"
