groupName: acme.vegasystems.de

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/rescaled/cert-manager-webhook-vegasystems
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

replicaCount: 1

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
